<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    </head>


    <?php
    $title = 'Editar Militar';
    $this->headTitle($title);
    ?>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <?php
    $nipInt = $nip; // guarda o nip como numerico

    $nip = $form->get('nip');
    $nip->setAttribute('class', 'form-control');
    $nip->setAttribute('placeholder', 'Entre com o NIP.');

    $posto = $form->get('posto');
    $posto->setAttribute('class', 'form-control');
    $posto->setAttribute('placeholder', 'Entre com o Posto.');

    $nome = $form->get('nome');
    $nome->setAttribute('class', 'form-control');
    $nome->setAttribute('placeholder', 'Entre com o Nome.');

    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');


    $form->setAttribute('action', $this->url('militar', [
                'action' => 'edit',
                'nip' => $nipInt,
    ]));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>

    <div class="form-group">
        <?= $this->formLabel($nip) ?>
        <?= $this->formElement($nip) ?>
        <?= $this->formElementErrors()->render($nip, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($posto) ?>
        <?= $this->formElement($posto) ?>
        <?= $this->formElementErrors()->render($posto, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($nome) ?>
        <?= $this->formElement($nome) ?>
        <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
    </div>


    <?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('nip'));
    echo $this->form()->closeTag();
    ?>
</html>

